# https://github.com/marketplace/actions/npm-publish
name: Publish Package to npm
on:
  release:
    types: [created]

env:
  VITE_SUPABASE_URL: ${{vars.SUPABASE_URL}}
  VITE_SUPABASE_KEY: ${{vars.SUPABASE_KEY}}
  VITE_HCAPTCHA_SITE_KEY: ${{vars.HCAPTCHA_SITE_KEY}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build-library
      - run: echo "Publishing to npm registry"
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
